#include "l298n.h"

uint32_t PWM = 82;

void L298N_Init(void)
{
	HAL_TIM_PWM_Start(&htim2,TIM_CHANNEL_3);
	HAL_TIM_PWM_Start(&htim2,TIM_CHANNEL_4);
	
	__HAL_TIM_SET_COMPARE(&htim2,TIM_CHANNEL_3,PWM);
	__HAL_TIM_SET_COMPARE(&htim2,TIM_CHANNEL_4,PWM);
	
	HAL_GPIO_WritePin(GPIOA,GPIO_PIN_7,0);
	HAL_GPIO_WritePin(GPIOA,GPIO_PIN_1,0);
	HAL_GPIO_WritePin(GPIOB,GPIO_PIN_9,0);
	HAL_GPIO_WritePin(GPIOB,GPIO_PIN_10,0);
}

void L298N_Go(void)
{
//	__HAL_TIM_SET_COMPARE(&htim2,TIM_CHANNEL_1,PWM);
//	__HAL_TIM_SET_COMPARE(&htim2,TIM_CHANNEL_2,0);
//	__HAL_TIM_SET_COMPARE(&htim2,TIM_CHANNEL_3,0);
//	__HAL_TIM_SET_COMPARE(&htim2,TIM_CHANNEL_4,PWM);
	
	HAL_GPIO_WritePin(GPIOA,GPIO_PIN_7,0);
	HAL_GPIO_WritePin(GPIOA,GPIO_PIN_1,1);
	HAL_GPIO_WritePin(GPIOB,GPIO_PIN_9,1);
	HAL_GPIO_WritePin(GPIOB,GPIO_PIN_10,0);
}

void L298N_Back(void)
{
//	__HAL_TIM_SET_COMPARE(&htim2,TIM_CHANNEL_1,0);
//	__HAL_TIM_SET_COMPARE(&htim2,TIM_CHANNEL_2,PWM);
//	__HAL_TIM_SET_COMPARE(&htim2,TIM_CHANNEL_3,PWM);
//	__HAL_TIM_SET_COMPARE(&htim2,TIM_CHANNEL_4,0);
	HAL_GPIO_WritePin(GPIOA,GPIO_PIN_7,1);
	HAL_GPIO_WritePin(GPIOA,GPIO_PIN_1,0);
	HAL_GPIO_WritePin(GPIOB,GPIO_PIN_9,0);
	HAL_GPIO_WritePin(GPIOB,GPIO_PIN_10,1);
}

void L298N_Left(void)
{
//	__HAL_TIM_SET_COMPARE(&htim2,TIM_CHANNEL_1,0);
//	__HAL_TIM_SET_COMPARE(&htim2,TIM_CHANNEL_2,PWM);
//	__HAL_TIM_SET_COMPARE(&htim2,TIM_CHANNEL_3,0);
//	__HAL_TIM_SET_COMPARE(&htim2,TIM_CHANNEL_4,PWM);
	HAL_GPIO_WritePin(GPIOA,GPIO_PIN_7,1);
	HAL_GPIO_WritePin(GPIOA,GPIO_PIN_1,0);
	HAL_GPIO_WritePin(GPIOB,GPIO_PIN_9,1);
	HAL_GPIO_WritePin(GPIOB,GPIO_PIN_10,0);
}

void L298N_Right(void)
{
//	__HAL_TIM_SET_COMPARE(&htim2,TIM_CHANNEL_1,PWM);
//	__HAL_TIM_SET_COMPARE(&htim2,TIM_CHANNEL_2,0);
//	__HAL_TIM_SET_COMPARE(&htim2,TIM_CHANNEL_3,PWM);
//	__HAL_TIM_SET_COMPARE(&htim2,TIM_CHANNEL_4,0);
	HAL_GPIO_WritePin(GPIOA,GPIO_PIN_7,0);
	HAL_GPIO_WritePin(GPIOA,GPIO_PIN_1,1);
	HAL_GPIO_WritePin(GPIOB,GPIO_PIN_9,0);
	HAL_GPIO_WritePin(GPIOB,GPIO_PIN_10,1);
}

void L298N_Stop(void)
{
//	__HAL_TIM_SET_COMPARE(&htim2,TIM_CHANNEL_1,0);
//	__HAL_TIM_SET_COMPARE(&htim2,TIM_CHANNEL_2,0);
//	__HAL_TIM_SET_COMPARE(&htim2,TIM_CHANNEL_3,0);
//	__HAL_TIM_SET_COMPARE(&htim2,TIM_CHANNEL_4,0);
	HAL_GPIO_WritePin(GPIOA,GPIO_PIN_7,0);
	HAL_GPIO_WritePin(GPIOA,GPIO_PIN_1,0);
	HAL_GPIO_WritePin(GPIOB,GPIO_PIN_9,0);
	HAL_GPIO_WritePin(GPIOB,GPIO_PIN_10,0);
}
